/*

 MAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 32 x 32
   Tile set      : D:\src\Retro\GameBoy\GBC-Samples\GBC-Palette\res\palette_test.gbr
   Plane count   : 2 planes (16 bits)
   Plane order   : Planes are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __Map_h_INCLUDE
#define __Map_h_INCLUDE

#define MapWidth 32
#define MapHeight 32
#define MapBank 0

#define Map MapPLN0
extern const unsigned char MapPLN0[];
extern const unsigned char MapPLN1[];

#endif

/* End of MAP.H */
