/*

 TILES.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 0

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : Constant per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __Tiles_h_INCLUDE
#define __Tiles_h_INCLUDE

/* Bank of tiles. */
#define PaletteTestTilesBank 0

/* Super Gameboy palette 0 */
#define PaletteTestTilesSGBPal0c0 6076
#define PaletteTestTilesSGBPal0c1 8935
#define PaletteTestTilesSGBPal0c2 6596
#define PaletteTestTilesSGBPal0c3 5344

/* Super Gameboy palette 1 */
#define PaletteTestTilesSGBPal1c0 6076
#define PaletteTestTilesSGBPal1c1 8935
#define PaletteTestTilesSGBPal1c2 6596
#define PaletteTestTilesSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define PaletteTestTilesSGBPal2c0 6076
#define PaletteTestTilesSGBPal2c1 8935
#define PaletteTestTilesSGBPal2c2 6596
#define PaletteTestTilesSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define PaletteTestTilesSGBPal3c0 6076
#define PaletteTestTilesSGBPal3c1 8935
#define PaletteTestTilesSGBPal3c2 6596
#define PaletteTestTilesSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define PaletteTestTilesCGBPal0c0 6076
#define PaletteTestTilesCGBPal0c1 8935
#define PaletteTestTilesCGBPal0c2 6596
#define PaletteTestTilesCGBPal0c3 5344

/* Gameboy Color palette 1 */
#define PaletteTestTilesCGBPal1c0 32767
#define PaletteTestTilesCGBPal1c1 31
#define PaletteTestTilesCGBPal1c2 992
#define PaletteTestTilesCGBPal1c3 31744

/* Gameboy Color palette 2 */
#define PaletteTestTilesCGBPal2c0 32767
#define PaletteTestTilesCGBPal2c1 31744
#define PaletteTestTilesCGBPal2c2 31
#define PaletteTestTilesCGBPal2c3 992

/* Gameboy Color palette 3 */
#define PaletteTestTilesCGBPal3c0 32767
#define PaletteTestTilesCGBPal3c1 992
#define PaletteTestTilesCGBPal3c2 31744
#define PaletteTestTilesCGBPal3c3 31

/* Gameboy Color palette 4 */
#define PaletteTestTilesCGBPal4c0 32767
#define PaletteTestTilesCGBPal4c1 32767
#define PaletteTestTilesCGBPal4c2 32767
#define PaletteTestTilesCGBPal4c3 32767

/* Gameboy Color palette 5 */
#define PaletteTestTilesCGBPal5c0 32767
#define PaletteTestTilesCGBPal5c1 1023
#define PaletteTestTilesCGBPal5c2 31775
#define PaletteTestTilesCGBPal5c3 32736

/* Gameboy Color palette 6 */
#define PaletteTestTilesCGBPal6c0 32767
#define PaletteTestTilesCGBPal6c1 32736
#define PaletteTestTilesCGBPal6c2 1023
#define PaletteTestTilesCGBPal6c3 31775

/* Gameboy Color palette 7 */
#define PaletteTestTilesCGBPal7c0 32767
#define PaletteTestTilesCGBPal7c1 31775
#define PaletteTestTilesCGBPal7c2 32736
#define PaletteTestTilesCGBPal7c3 1023

/* CGB palette entries. */
#define PaletteTestTilesCGB0 1
/* Start of tile array. */
extern const unsigned char PaletteTestTiles[];

#endif

/* End of TILES.H */
