/*

 TILES.C

 Tile Source File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 0

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : Constant per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

/* Start of tile array. */
const unsigned char PaletteTestTiles[] =
{
  0x00,0x00,0x0E,0x00,0x0E,0x00,0x0E,0x00,
  0x0E,0x7E,0x0E,0x7E,0x0E,0x7E,0x00,0x00
};

/* End of TILES.C */
