//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_DmgScreenTiles_H
#define METASPRITE_DmgScreenTiles_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define DmgScreenTiles_TILE_ORIGIN 0
#define DmgScreenTiles_TILE_W 8
#define DmgScreenTiles_TILE_H 8
#define DmgScreenTiles_WIDTH 64
#define DmgScreenTiles_HEIGHT 96
#define DmgScreenTiles_TILE_COUNT 88
#define DmgScreenTiles_PALETTE_COUNT 1
#define DmgScreenTiles_COLORS_PER_PALETTE 4
#define DmgScreenTiles_TOTAL_COLORS 4

BANKREF_EXTERN(DmgScreenTiles)

extern const palette_color_t DmgScreenTiles_palettes[4];
extern const uint8_t DmgScreenTiles_tiles[1408];


#endif
