//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_Logo_H
#define METASPRITE_Logo_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define Logo_TILE_ORIGIN 0
#define Logo_TILE_W 8
#define Logo_TILE_H 8
#define Logo_WIDTH 8
#define Logo_HEIGHT 8
#define Logo_TILE_COUNT 89
#define Logo_PALETTE_COUNT 1
#define Logo_COLORS_PER_PALETTE 4
#define Logo_TOTAL_COLORS 4
#define Logo_MAP_ATTRIBUTES 0

BANKREF_EXTERN(Logo)

extern const palette_color_t Logo_palettes[4];
extern const uint8_t Logo_tiles[1424];

extern const unsigned char Logo_map[360];

#endif
